apiVersion: v1
kind: Service
metadata:
  name: message-router
  namespace: message-router
  labels:
    app: message-router
spec:
  type: ClusterIP
  selector:
    app: message-router
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
